src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls.static import static
from django.urls import path

from blog import settings
from posts.views import BlogHome, BlogPostCreate, BlogPostEdit, BlogPostDetail, BlogPostDelete

app_name = 'posts'

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('edit/<slug:slug>/', BlogPostEdit.as_view(), name='edit'),
    path('view/<slug:slug>/', BlogPostDetail.as_view(), name='view'),
    path('delete/<slug:slug>/', BlogPostDelete.as_view(), name='delete'),
]

src/posts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='Publié')
    content = models.TextField(blank=True, verbose_name='Contenu')
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    objects = models.Manager()

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def get_author_or_default(self):
        return self.author if self.author else "L'auteur inconnu"

    @property
    def get_created_on_or_default(self):
        return self.created_on if self.created_on else ''

    def get_absolute_url(self):
        return reverse('posts:home')

src/posts/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from posts.models import BlogPost


# Create your views here.
class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)


@method_decorator(login_required, name='dispatch')
class BlogPostCreate(CreateView):
    model = BlogPost
    fields = ['title', 'content', 'thumbnail', ]
    template_name = 'posts/blogpost_create.html'


@method_decorator(login_required, name='dispatch')
class BlogPostEdit(UpdateView):
    model = BlogPost
    fields = ['title', 'content', 'published', 'thumbnail', ]
    template_name = 'posts/blogpost_edit.html'


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = 'posts/blogpost_detail.html'
    context_object_name = 'post'


@method_decorator(login_required, name='dispatch')
class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = 'post'
    success_url = reverse_lazy('posts:home')

src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Supprimer un article{% endblock %}

{% block content %}

  <h1>Supprimer un article</h1>

  <p>Voulez vous vraiment supprimer l'article '{{ post }}' </p>

  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Oui, supprimer" class="btn btn-delete">
  </form>

{% endblock %}

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}Creer un article{% endblock %}

{% block content %}

    <h1>Creer un article</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Creer l'article" class="btn btn-submit">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }} {% endblock %}

{% block content %}
    <article class="post-detail">
        <h1>{{ post.title }}</h1>
        {% if post.thumbnail %}
        <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}">
        {% endif %}
        <div>{{ post.content|linebreaks|safe }}</div>
    </article>
{% endblock %}

src/posts/templates/posts/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}Editer un article{% endblock %}

{% block content %}

    <h1>Editer un article</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Editer l'article" class="btn btn-submit">
    </form>

{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}Mes articles{% endblock %}

{% block content %}

<h1>Le Blog de Luna Nera</h1>

{% for post in posts %}
    <article>

        <div class="post-title">
            <h2>{{ post.title }}</h2>

            {% if request.user.is_authenticated %}
            <div>
                <a href="{% url 'posts:edit' slug=post.slug %}">Editer</a>
                <a href="{% url 'posts:delete' slug=post.slug %}">Supprimer</a>
            </div>
            {% endif %}
        </div>

        <h5 class="post-author">Publié par <i>{{ post.get_author_or_default }}</i> le {{ post.get_created_on_or_default }}</h5>
        <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>

        <form action="{% url 'posts:view' slug=post.slug %}">
            <button class="btn btn-submit">Lire l'article</button>
        </form>
    </article>
{% endfor %}

{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <nav>
        <a href="{% url 'posts:home' %}">Accueil</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>

    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>

</body>
</html>